package com.emras.inventory.entity;
import jakarta.persistence.*;
import lombok.*;
import java.time.Instant;
/**
 * Outbox Pattern implementation.
 *
 * Instead of calling Kafka directly inside a @Transactional method,
 * we write the event to this table in the SAME transaction as the
 * inventory update. A scheduler then reads unpublished events and
 * sends them to Kafka.
 *
 * This guarantees:
 *  - If DB commit fails → event is never written → Kafka never called ✓
 *  - If Kafka fails → event stays in outbox → retried next cycle ✓
 *  - DB and Kafka are always consistent ✓
 *
 * Why this matters:
 *  Without the Outbox:
 *    1. DB update commits ✓
 *    2. Kafka publish fails ✗
 *    → Stock changed but downstream services never notified
 *
 *  With the Outbox:
 *    1. DB update + outbox INSERT commit together ✓ or ✗ (atomic)
 *    2. Scheduler reads outbox → publishes to Kafka
 *    3. If Kafka fails → event stays PENDING → retried next cycle
 *    → Guaranteed eventual delivery ✓
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "outbox_events", schema = "schema_inventory",
        indexes = {
                @Index(name = "idx_outbox_status",     columnList = "status"),
                @Index(name = "idx_outbox_created",    columnList = "created_at"),
                @Index(name = "idx_outbox_event_id",   columnList = "event_id", unique = true)
        })
public class OutboxEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Globally unique event ID — used by consumers for idempotency.
     * Generated by the service at write time using UUID.
     */
    @Column(name = "event_id", nullable = false, unique = true, length = 36)
    private String eventId;

    /** Kafka topic to publish to */
    @Column(nullable = false, length = 100)
    private String topic;

    /** Kafka message key (e.g. SKU or orderId) */
    @Column(name = "message_key", length = 100)
    private String messageKey;

    /** JSON payload to publish */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String payload;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    @Builder.Default
    private OutboxStatus status = OutboxStatus.PENDING;

    /** How many times publishing has been attempted */
    @Column(nullable = false)
    @Builder.Default
    private int retryCount = 0;

    /** Timestamp of last publish attempt */
    private Instant lastAttemptAt;

    /** Set when permanently failed after max retries */
    private Instant failedAt;

    @Column(length = 500)
    private String errorMessage;

    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    private Instant publishedAt;

    public enum OutboxStatus {
        PENDING,    // waiting to be published
        PUBLISHED,  // successfully sent to Kafka
        FAILED      // max retries exceeded — needs manual intervention
    }

    @PrePersist
    protected void onCreate() {
        this.createdAt = Instant.now();
    }
}